version: '3.9'
services:
  mongo_db:
    container_name: mongodb
    image: tmotlim/tech-radar-docker-repo:mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - tech-radar-network

networks:
  tech-radar-network:
    name: tech-radar-network
    driver: bridge

volumes:
  mongo_db : {}